### ISSUE TITLE
Varieties of seeds

### ISSUE THREAD

**Issue by Catalonium** [Catalonium/PlantGrower#5]
3 types of seeds

**Comment by developernca** [comment]
Just explanation for me, assignee.

Pumpkin = have to be watered after 5 secs, full growth in 15 secs, 2 points earned after harvest
Cucumber = have to be watered after 7 secs, full growth in 10 secs, 1 point earned
etc.
To make the mechanics more richer, fun and involved
For example if you fail to water, the crop will die and you have to click on it to clear that soil block, with no points awarded

**Comment by Catalonium** [comment]
@developernca Seeds set-up completed, only score and watering time is to be decided and set per prefab
